import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

import axios from "axios";
import InstagramEmbed from "react-instagram-embed";
import passport from "passport";
import InstagramStrategy from "passport-instagram";
import session from "express-session";
import dotenv from "dotenv";
import fs from "fs";
const inter = Inter({ subsets: ["latin"] });

dotenv.config();

// Configure the passport middleware
const CALLBACK_URL = "https://instagram-jade-iota.vercel.app/";

passport.serializeUser((user, done) => {
  done(null, user);
});

passport.deserializeUser((obj, done) => {
  done(null, obj);
});

passport.use(
  new InstagramStrategy(
    {
      clientID: "618692533418907",
      clientSecret: "ec3c052b63c820dc13b9a78ca52d65ea",
      callbackURL: CALLBACK_URL,
    },
    (accessToken, refreshToken, profile, done) => {
      process.nextTick(() => done(null, { accessToken, profile }));
    }
  )
);

// Define the authentication middleware function
export const authenticate = (req, res, next) => {
  passport.authenticate("instagram")(req, res, next);
};

// Define the middleware configuration object
export const config = {
  api: {
    bodyParser: false,
  },
};

// Define the middleware array
export const middleware = [
  session({
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: true,
  }),
  passport.initialize(),
  passport.session(),
];

// Define the Photos component that displays the user's photos
export function Photos({ photos }) {
  return (
    <div>
      <h1>Your Photos</h1>
      <div>
        {photos.map((photo) => (
          <div key={photo.id}>
            <InstagramEmbed url={photo.url} />
            <p>{photo.caption}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

// Define the getServerSideProps function that fetches the user's photos
export async function getServerSideProps({ req }) {
  if (!req.user) {
    // Redirect to the authentication route if user is not authenticated
    return {
      redirect: {
        destination: "/api/auth/instagram",
        permanent: false,
      },
    };
  }

  // Fetch the user's photos using the Instagram API
  const { accessToken } = req.user;
  const { data } = await axios.get(
    `https://api.instagram.com/v1/users/self/media/recent/?access_token=${accessToken}`
  );
  const photos = data.data.map((photo) => ({
    id: photo.id,
    url: photo.images.standard_resolution.url,
    caption: photo.caption ? photo.caption.text : null,
  }));

  return {
    props: {
      photos,
    },
  };
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
